### ISSUE TITLE
Migrate repository to organization

### ISSUE THREAD

**Issue by robert-wagner** [jvmancuso/CAIG#3]
Storing repository in an organization page allows for taking advantage of github pages and advanced permissions without having them be a subset of Jasons Github account.

Additionally gives people who contribute to the group a badge to display on their github profile showing they are a member of the Cleveland AI Group

**Comment by jvmncs** [comment]
+1.  Wasn't sure how active other people were gonna be on this repo, but assuming that continues we'll definitely do that.  I'll keep this open until then.

**Comment by jvmncs** [comment]
:+1:
