### ISSUE TITLE
Create Website Using Jekyll and Github Pages

### ISSUE THREAD

**Issue by robert-wagner** [jvmancuso/CAIG#4]
Jekyll allows current markdown files to be automatically converted to static html pages for easier viewing.

Github pages allows for free hosting of these pages and provides jekyll integration

**Comment by jvmncs** [comment]
How much maintenance is required for this?  It seems like a good idea for people who aren't as familiar with GitHub, but I don't want usability/utility to suffer as a result of poor upkeep.

Also, I kind of like the idea of having members becoming familiar with git and GitHub by interacting with the group, although I don't think this suggestion prevents anyone from doing that if they want to.

**Comment by robert-wagner** [comment]
Setting it up takes a very short period of time. All that is required for setup is creating a gemfile and config file which do not need to be changed after the initial setup. I can take care of creating these files. Additionally, the project needs to be opened as a github pages site which is a checkbox in the setting

Other than the setup a small heading needs to added to each file you want to be a webpage but that heading is similar for every file. Creating a template to create posts would not be difficult

**Comment by jvmncs** [comment]
How easy would it be for people to download files hosted elsewhere within the repository?

**Comment by robert-wagner** [comment]
Exactly the same as it is currently. The repository remains exactly the same except for the modifications mentioned above. Github just processes the markdown files with headers to create a webpage as well

**Comment by jvmncs** [comment]
Sounds good, I'll tackle #3 after dinner and close it when I'm done.

**Comment by robert-wagner** [comment]
Sounds good. I'll prepare a pull request with the necessary setup files

**Comment by jvmncs** [comment]
There's one person preparing a PR, after that's in I'll go ahead and migrate the repo.

**Comment by jvmncs** [comment]
Migrated
